url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "" # the name of your site, e.g. ACME Corp.

plugins:
  - jekyll-postcss
  - jekyll-multiple-languages-plugin

languages: ["en", "pt", "cn"]

exclude_from_localizations: ["javascript", "images", "css"]

postcss:
  cache: false

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
